name: Build and Deploy to Docker

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '18.17.x'
    - name: NPM Install dependancies        
      run: npm install
    - name: NPM Build
      run: npm run build
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}      
    - name: Build the Docker image
      run: |
        # Read Docker settings from config file
        DOCKER_USERNAME=$(node -e "const settings = require('./src/config/settings'); console.log(settings.podcastSettings.deployment.docker.username);")
        DOCKER_IMAGE=$(node -e "const settings = require('./src/config/settings'); console.log(settings.podcastSettings.deployment.docker.imageName);")
        
        # Build the Docker image
        docker build -t $DOCKER_USERNAME/$DOCKER_IMAGE:latest .
    - name: Push the docker image
      run: |
        # Read Docker settings from config file
        DOCKER_USERNAME=$(node -e "const settings = require('./src/config/settings'); console.log(settings.podcastSettings.deployment.docker.username);")
        DOCKER_IMAGE=$(node -e "const settings = require('./src/config/settings'); console.log(settings.podcastSettings.deployment.docker.imageName);")
        
        # Push the Docker image
        docker push $DOCKER_USERNAME/$DOCKER_IMAGE:latest
